Update LLVM 4.0 & added pictures
mykter/afl-training pull request #2
Opened 2019-01-28 17:24 UTC by enovella

2019-02-04 12:09 UTC, mykter requested changes
Thanks for the PR! Glad to see it works with clang 4.0, happy to merge in that part of the request.
I've left some comments against the other parts.

I hope you found it useful. How did you come across it, out of interest?

2019-02-04 12:09 UTC, mykter commented on quickstart/README.md
> +    $ ~/afl-2.45b/afl-fuzz -i in -o out ./vulnerable
the folder is called inputs in this case

2019-02-04 12:09 UTC, mykter commented on quickstart/README.md
> +Without instrumentation (`-n`): (`afl-fuzz -i inputs -o out -n ./vulnerable`)
Whilst it's an interesting comparison, I don't think I want to go into the differences between these two modes in the quickstart - we just want to have the bare minimum to get started fuzzing.

2019-02-04 12:09 UTC, mykter commented on quickstart/README.md
> +![imaing](https://github.com/enovella/afl-training/blob/master/quickstart/pics/afl-pic-vulnerable.png)
A screenshot is a nice idea, thanks. I've added one to master that shows the status once all three easily findable crashes have been detected.

2019-05-15 09:01 UTC, andronat commented
Hey @enovella! Any news on this?

2019-05-15 15:27 UTC, enovella commented
Sorry but I am extremely busy at the moment with other things.

2019-05-19 19:33 UTC, mykter commented
I've updated the Dockerfile to LLVM 6, so closing this now.

2019-05-19 19:33 UTC, closed without merging